apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: linkerd
  chart:
    git: https://github.com/dstrebel/cluster-config
    path: workloads/charts/linkerd2
    ref: master
  # values:
  #  global:
    # url of existing prometheus
  #    prometheusUrl: "prometheus-k8s.monitoring.svc.cluster.local"
  # url of external grafana instance.
  #    grafanaUrl: "grafana.monitoring.svc.cluster.local"
  ####    enabled: true
